# Generated by Django 6.1.1 on 2026-09-21 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('serving_description', models.CharField(blank=True, max_length=200)),
                ('serving_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fiber_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('ai', 'AI estimate'), ('database', 'Food database')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_foods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='snack', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('ai', 'AI estimate'), ('database', 'Food database')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_logs', to='assistant.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_items', to='nutrition.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.meallog')),
            ],
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name'], name='nutrition_f_name_caa2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['user', 'date'], name='nutrition_m_user_id_c8e84a_idx'),
        ),
    ]
